---
- name: Copy Nginx config
  template:
    src: nginx.conf.j2
    dest: "{{ playbook_dir }}/../nginx.conf"
  notify:
    - Restart Nginx

- name: Start docker containers
  shell: docker-compose up -d
  args:
    chdir: "{{ playbook_dir }}/.."

- name: Restart Nginx (inside container)
  shell: docker-compose restart nginx
  args:
    chdir: "{{ playbook_dir }}/.."