---
- name: Ensure Docker is installed on Linux
  apt:
    name: docker.io
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure Docker is installed on macOS
  homebrew:
    name: docker
    state: present
  become: false
  when: ansible_facts['os_family'] == "Darwin"

